### PR TITLE
Vladp/change phone number format

### PR DESCRIPTION
**Pull request by MrVenik**
## Summary
Update the phone number format from `XX-XXX-XX-XX`, where each `X` represents a digit, to the international format `+CCC-XX-XXX-XX-XX`, where `C` denotes the country code. The new format supports phone numbers with lengths ranging from 7 (the shortest possible) to 15 digits.

## Remarks
I decided to create my own validation attribute because the existing one relied on regular expressions, which could occasionally be slow. Instead of using the [default implementation](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.phoneattribute?view=net-8.0), I benchmarked my approach against other implementations, including regular expressions and the default method. My custom variant proved to be faster, so I decided to go with it.

**Benchmark  source code:** https://github.com/MrVenik/PhoneNumberValidation
**Benchmark results:** 
image

### CODE REVIEW

**Comment by MrVenik** [comment]
Migrations include many instances of `migrationBuilder.AlterColumn<DateTimeOffset>`.
I’m not sure why `dotnet-ef migrations add` inserts this code into the migration.
If it’s a critical issue, we can consider reverting the last commit.

**Comment by VadymLevkovskyi** [comment]
> Migrations include many instances of `migrationBuilder.AlterColumn<DateTimeOffset>`. I’m not sure why `dotnet-ef migrations add` inserts this code into the migration. If it’s a critical issue, we can consider reverting the last commit.

This change (from datetime to datetime(6)) seems to be a correct one (just introduced in wrong PR), the only thing I'm worriing is dataloss, have you checked whether datetime data remains correct after migration?

The same issue is also related to your changes done for phone. But thy are more "broken". Before changes "380" was prefixed during phone number mapping (in code), now that part of code is removed and thus user will see old numbers "cropped". 

Please consider if old phone numbers data should be changed as a part of migration up/down.

**Comment by MrVenik** [comment]
> > Migrations include many instances of `migrationBuilder.AlterColumn<DateTimeOffset>`. I’m not sure why `dotnet-ef migrations add` inserts this code into the migration. If it’s a critical issue, we can consider reverting the last commit.
> 
> This change (from datetime to datetime(6)) seems to be a correct one (just introduced in wrong PR), the only thing I'm worriing is dataloss, have you checked whether datetime data remains correct after migration?
> 
> The same issue is also related to your changes done for phone. But thy are more "broken". Before changes "380" was prefixed during phone number mapping (in code), now that part of code is removed and thus user will see old numbers "cropped".
> 
> Please consider if old phone numbers data should be changed as a part of migration up/down.

I am not sure about data loss, but based on my understanding and the information in the [MySQL documentation](https://dev.mysql.com/doc/refman/8.3/en/datetime.html), the `datetime(6)` data type offers greater precision than the standard `datetime`. Therefore, there should be no risk of data loss. The same migration issue can be found in #1408.

As for phone numbers in the database that are not prefixed with `+CCC`, we discussed this during our daily meeting. The decision was to manually add the appropriate prefix to the existing phone numbers in the database.

**Comment by MrVenik** [comment]
> > Migrations include many instances of `migrationBuilder.AlterColumn<DateTimeOffset>`. I’m not sure why `dotnet-ef migrations add` inserts this code into the migration. If it’s a critical issue, we can consider reverting the last commit.
> 
> This change (from datetime to datetime(6)) seems to be a correct one (just introduced in wrong PR), the only thing I'm worriing is dataloss, have you checked whether datetime data remains correct after migration?
> 
> The same issue is also related to your changes done for phone. But thy are more "broken". Before changes "380" was prefixed during phone number mapping (in code), now that part of code is removed and thus user will see old numbers "cropped".
> 
> Please consider if old phone numbers data should be changed as a part of migration up/down.

Now migration does not include any `datetime` changes.

**Comment by MrVenik** [comment]
@VadymLevkovskyi Can you review and provide feedback? Thank you!

**Review by VadymLevkovskyi — APPROVED** [review]

**Pull request merged**
