### PR TITLE
Move business logic stuff from WebApi into separate project

### PR DESCRIPTION
**Pull request by MrVenik**
# Summary
In this pull request, the proposed changes involve separating the business logic from the API project to enhance code reusability. By isolating business logic, we can efficiently reuse components across different parts of the application or even in other projects. For instance:
- Moving Quartz Jobs into a separate project.
- Segregating provider-related admin APIs into their own project.
# Architecture Comparison:
- Old Architecture:
oos_arch_old
- New Architecture (proposed with this PR):
oos_arch_new

### CODE REVIEW

**Comment by VadymLevkovskyi** [comment]
Hasn't checked everything yet. Have few considerations/questions:

1. Is test coverage in scope of this PR?
2. Is fixing Sonar-reported issues in scope of this PR?
3. What is the rationale to not use "clean" design?

More about the last question.

Your suggested approach is (arrows shows usage): `Common` ← `DataAccess` ← `BusinessLogic` ← `WebApi`. 
Taking into account `ProjectReference` section of `BusinessLogic.csproj` 
<details>
  <summary>there are even more dependencies</summary> 

```
    <ProjectReference Include="..\OutOfSchool.Common\OutOfSchool.Common.csproj" />
    <ProjectReference Include="..\OutOfSchool.DataAccess\OutOfSchool.DataAccess.csproj" />
    <ProjectReference Include="..\OutOfSchool.ElasticsearchData\OutOfSchool.ElasticsearchData.csproj" />
    <ProjectReference Include="..\OutOfSchool.EmailSender\OutOfSchool.EmailSender.csproj" />
    <ProjectReference Include="..\OutOfSchool.GRPC\OutOfSchool.GRPC.csproj" />
    <ProjectReference Include="..\OutOfSchool.RazorTemplatesData\OutOfSchool.RazorTemplatesData.csproj" />
    <ProjectReference Include="..\OutOfSchool.Redis\OutOfSchool.Redis.csproj" />
```
</details>

than simple `DataAccess`. 

It is well-known layered design, having well-known nuance that **upper layer is dependent on lower layers** and thus each changes done beneath could affect it.

What if we redirect arrow and make the `BusinessLogic` the core "layer"? 
Like `DataAccess (and other Elastic/Redis/... guys)` → `BusinessLogic` ← `WebApi`.

Yes, it requires massive changes (and that's why I'm asking this question here, as you've already done similar task).
Main benefit - it gives better (lower) coupling, as `BL` would know nothing about implementations details of caching, storage, etc. (Better testability included)
Main issue - it might require more choreography in the code and bit worse performance.

@DmyMi please join this discussion.

**Comment by MrVenik** [comment]
> Hasn't checked everything yet. Have few considerations/questions:
> 
> 1. Is test coverage in scope of this PR?
> 2. Is fixing Sonar-reported issues in scope of this PR?
> 3. What is the rationale to not use "clean" design?
> 
> More about the last question.
> 
> Your suggested approach is (arrows shows usage): `Common` ← `DataAccess` ← `BusinessLogic` ← `WebApi`. Taking into account `ProjectReference` section of `BusinessLogic.csproj`
> 
> there are even more dependencies
> than simple `DataAccess`.
> 
> It is well-known layered design, having well-known nuance that **upper layer is dependent on lower layers** and thus each changes done beneath could affect it.
> 
> What if we redirect arrow and make the `BusinessLogic` the core "layer"? Like `DataAccess (and other Elastic/Redis/... guys)` → `BusinessLogic` ← `WebApi`.
> 
> Yes, it requires massive changes (and that's why I'm asking this question here, as you've already done similar task). Main benefit - it gives better (lower) coupling, as `BL` would know nothing about implementations details of caching, storage, etc. (Better testability included) Main issue - it might require more choreography in the code and bit worse performance.
> 
> @DmyMi please join this discussion.

1. I believe that test coverage isn’t directly related to this pull request (PR). Since the files in this PR haven’t changed significantly (or have only minor modifications), writing tests in this PR might be redundant work.
2. The same reasoning applies to Sonar issues. However, I’d make an exception for issues related to `usings` in files or anything directly tied to the proposed architecture.
3. I absolutely agree that adopting a clean design would be more appropriate. However, it’s essential to recognize that these changes aren’t as straightforward as copy-pasting. Therefore, I propose an incremental approach: Start with the current architecture -> Introduce the architecture from this PR -> Gradually transition to clean architecture.

UPD:
Below is an architectural diagram that I propose. Please note that this is not the final version, and it requires further discussion (sorry, arrows are inverted):
oos_arch_clean

**Comment by VadymLevkovskyi** [comment]
> > ... (cut)
> 
> UPD: Below is an architectural diagram that I propose. Please note that this is not the final version, and it requires further discussion (sorry, arrows are inverted): oos_arch_clean

Nice diagram, thanks for sharing. One small comment: please draw such diagrams in reverse order (upside-down), where commonly used things are at the bottom and application/infrastructure/UI level is on the top.

**Review by VadymLevkovskyi — APPROVED** [review]
PR is approved, though quality of my review is pretty bad (big PR, can't spend half a day or even more for 1 PR review).

Have few comments if any similar tasks will be done later:
- please make PR smaller, splitting by commits is good, but you could also split it into chain of PRs (github works awfully with such big PRs)
- please don't mix different actions in one commit (there is a "Move Services, Hubs and some fixes" commit, and looking into the commit I can't find what "fixes' were done in moved file)
- please consider making smaller but more "correct" PRs instead of big "mechanical" approach - thus you let coleagues to earlier jump into new correct code (smaller scope, but higher quality), instead of thinking that whole new code is correct while it's not 

For this specific task I've found unexpected code changes, please reconsider if they are purposed or has to be fixed:
- global usings of `BusinessLogic` contains lot of `Microsoft.AspNetCore.*` - I believe it's a smell, and all code requiring these usings should remain in `WebApi`;
- presence of UI/infrastructure-level attributes on `BusinessLogic` models (like `[DisplayName]`, `[JsonProperty]`, `[DataType]`) - it's not a part of business logic

**Comment by MrVenik** [comment]
> PR is approved, though quality of my review is pretty bad (big PR, can't spend half a day or even more for 1 PR review).
> 
> Have few comments if any similar tasks will be done later:
> 
> * please make PR smaller, splitting by commits is good, but you could also split it into chain of PRs (github works awfully with such big PRs)
> * please don't mix different actions in one commit (there is a "Move Services, Hubs and some fixes" commit, and looking into the commit I can't find what "fixes' were done in moved file)
> * please consider making smaller but more "correct" PRs instead of big "mechanical" approach - thus you let coleagues to earlier jump into new correct code (smaller scope, but higher quality), instead of thinking that whole new code is correct while it's not
> 
> For this specific task I've found unexpected code changes, please reconsider if they are purposed or has to be fixed:
> 
> * global usings of `BusinessLogic` contains lot of `Microsoft.AspNetCore.*` - I believe it's a smell, and all code requiring these usings should remain in `WebApi`;
> * presence of UI/infrastructure-level attributes on `BusinessLogic` models (like `[DisplayName]`, `[JsonProperty]`, `[DataType]`) - it's not a part of business logic

Thank you for your feedback on improving work with commits, pull requests (PRs), and Git in general!

If necessary, I can close this PR and split changes into smaller PRs. For example, one PR could focus on moving models, while another could handle services. This approach might improve understanding of specific changes.

I understand that using `Microsoft.AspNetCore.*` in the `BL` is smell, but there are some models that rely on `IFormFile` and other components that use `Microsoft.AspNetCore.*`. In this PR, I’ve focused only on architectural changes, as I believe that this is appropriate way. Same with attributes like `[DisplayName]`, `[JsonProperty]`, `[DataType]`.

**Comment by MrVenik** [comment]
> > > ... (cut)
> > 
> > 
> > UPD: Below is an architectural diagram that I propose. Please note that this is not the final version, and it requires further discussion (sorry, arrows are inverted): oos_arch_clean
> 
> Nice diagram, thanks for sharing. One small comment: please draw such diagrams in reverse order (upside-down), where commonly used things are at the bottom and application/infrastructure/UI level is on the top.

Got it! I will apply your suggestions next time, thanks!

**Comment by VadymLevkovskyi** [comment]
> > ... (cut)
> 
> Thank you for your feedback on improving work with commits, pull requests (PRs), and Git in general!
> 
> If necessary, I can close this PR and split changes into smaller PRs. For example, one PR could focus on moving models, while another could handle services. This approach might improve understanding of specific changes.
> 
> I understand that using `Microsoft.AspNetCore.*` in the `BL` is smell, but there are some models that rely on `IFormFile` and other components that use `Microsoft.AspNetCore.*`. In this PR, I’ve focused only on architectural changes, as I believe that this is appropriate way. Same with attributes like `[DisplayName]`, `[JsonProperty]`, `[DataType]`.

Just create a tech debt/other ticket to not forget to fix it later. Creating extra PRs from this one would require me to rereview them and I'm already sick and tired ;)

Regarding specific IFormFile question - I agree with this [StackOverflow answer](https://stackoverflow.com/questions/77675962/how-to-avoid-iformfile-dependency-in-application-layer)

**Comment by MrVenik** [comment]
> > > ... (cut)
> > 
> > 
> > Thank you for your feedback on improving work with commits, pull requests (PRs), and Git in general!
> > If necessary, I can close this PR and split changes into smaller PRs. For example, one PR could focus on moving models, while another could handle services. This approach might improve understanding of specific changes.
> > I understand that using `Microsoft.AspNetCore.*` in the `BL` is smell, but there are some models that rely on `IFormFile` and other components that use `Microsoft.AspNetCore.*`. In this PR, I’ve focused only on architectural changes, as I believe that this is appropriate way. Same with attributes like `[DisplayName]`, `[JsonProperty]`, `[DataType]`.
> 
> Just create a tech debt/other ticket to not forget to fix it later. Creating extra PRs from this one would require me to rereview them and I'm already sick and tired ;)
> 
> Regarding specific IFormFile question - I agree with this [StackOverflow answer](https://stackoverflow.com/questions/77675962/how-to-avoid-iformfile-dependency-in-application-layer)

Got it! Thank you for your hard work! :)
In future I will apply your suggestions and will organize PRs in better way
And sorry for bothering you :)

**Pull request merged**
