### PR TITLE
Kymachynskyi/Fix Argument Null Exception when SendgridApiKey is empty

### PR DESCRIPTION
**Pull request by DKymachynskyi**

### CODE REVIEW

**Review by VadymLevkovskyi — APPROVED** [review]
Approved, though I see here potential for unit test writing.

**Comment by DKymachynskyi** [comment]
> Approved, though I see here potential for unit test writing.

Thank you! @VadymLevkovskyi, I want to clarify that these should be integration tests that verify the inclusion of EmailSender in services under various parameters of AddEmailSender?

**Comment by VadymLevkovskyi** [comment]
> ... I want to clarify that these should be integration tests that verify the inclusion of EmailSender in services ...?

Yes @DKymachynskyi , it could be check that EmailSenderClientOptions are correct, though probablity of this test to be failed is quite low. That's why I don't insist on writing it.

**Comment by DKymachynskyi** [comment]
> > ... I want to clarify that these should be integration tests that verify the inclusion of EmailSender in services ...?
> 
> Yes @DKymachynskyi , it could be check that EmailSenderClientOptions are correct, though probablity of this test to be failed is quite low. That's why I don't insist on writing it.

@VadymLevkovskyi I've added tests. Thank you!

**Pull request merged**
