### PR TITLE
Add new state to ShowBlocked of ApplicationFilter

### PR DESCRIPTION
**Pull request by alrom**

### CODE REVIEW

**Comment by VadymLevkovskyi** [comment]
Logic seems OK. 
What about unit tests?

**Comment by alrom** [comment]
We never tested filters which use for making predicates. I'll search for how to check the predicate condition.
Could you approve this PR and leave unit tests like my tech debt? Because front needs these changes.

**Comment by VadymLevkovskyi** [comment]
> We never tested filters which use for making predicates. I'll search for how to check the predicate condition. Could you approve this PR and leave unit tests like my tech debt? Because front needs these changes.

1. As changes were done in private predicate building method you should check not the method, but data returned by service. I.e. results of `ApplicationService.GetAll()` called with different `filter.ShowBlocked` values on known collection.
2. I've checked the existing unit-tests and see 8 tests for mentioned `ApplicationService.GetAll()`. I belive it's really simple task to add another 3 tests for different `ShowBlocked` values. 
3. I doubt that front requires code without unit-tests. Please never use this as an excuse. 

Approved, though disappointed

**Review by VadymLevkovskyi — APPROVED** [review]

**Comment by alrom** [comment]
I added tests

**Comment by VadymLevkovskyi** [comment]
> I added tests

Thanks, man

**Pull request merged**
