### PR TITLE
Added notification count sending to NotificationHub

### PR DESCRIPTION
**Pull request by olsavchenk**
Follow-up for (https://github.com/ita-social-projects/OoS-Frontend/issues/2294)
Goal for this PR is to update notification count using WebSocket through SignalR.

Example of sent data:
```
{
   "type":1,
   "target":"ReceiveNotification",
   "arguments":[
      "{\"unreadNotificationsCount\":2,\"newNotificationDto\":{\"Id\":\"08dc79c9-f420-4795-85ce-534b46c12bef\",\"UserId\":\"string\",\"Data\":{\"additionalProp1\":\"string\",\"additionalProp2\":\"string\",\"additionalProp3\":\"string\"},\"Type\":\"Application\",\"Action\":\"Unknown\",\"CreatedDateTime\":\"2024-05-21T19:12:27.0712675+00:00\",\"ReadDateTime\":null,\"ObjectId\":\"3fa85f64-5717-4562-b3fc-2c963f66afa6\"}}"
   ]
}
  ```

### CODE REVIEW

**Review by VadymLevkovskyi — CHANGES_REQUESTED** [review]
(Tests coverage) Could any tests be written here to assure that message(s) to specific user/users are sent and have `unreadNotificationCount` field set? 

If you don't have better ideas - some clues for unit-tests design could be taken from [SO - unit testing .net core 2.2 SignalR hub issue with HubContext](https://stackoverflow.com/questions/57577371/unit-testing-net-core-2-2-signalr-hub-issue-with-hubcontext), it's not ideal but could be a start.

**Comment by olsavchenk** [comment]
As I believe this code is pretty much untestable. The issue is that ClientProxyExtensions class(for SendAsync method) block for some reason setupping and verifying using Moq, i.e. we get Exception:
```
System.NotSupportedException : Unsupported expression: ... => ....SendAsync(It.IsAny<string>(), It.IsAny<CancellationToken>())
Extension methods (here: ClientProxyExtensions.SendAsync) may not be used in setup / verification expressions.
```
Although based on stackoverflow answers you've provided I added assertions to check whether specific Groups were triggered.

**Comment by VadymLevkovskyi** [comment]
> As I believe this code is pretty much untestable. The issue is that ClientProxyExtensions class(for SendAsync method) block for some reason setupping ...

Everything is possible ;) 

`.Setup()` for extension method is blocked because it's not the part of the mocked object and moreover is a static method (that can't be mocked). But you could go deeper and check what is called by that extension method - either reading source code or checking invocations list (`mock.Invocations`) for the mocked object. And `.Setup()`/`.Verify()` that invocations. See code below.

```
    [Test]
    public async Task Create_RecipientsIdsValid_CreatesSpecificNumberOfTimesAndSendNotifications()
    {
        // Arrange
        var faker = new Faker();
        var recipientsIds = faker.Make(faker.Random.Int(1, 10), () => Guid.NewGuid().ToString());

        var notificationsConfig = new NotificationsConfig
        {
            Enabled = true,
        };

        notificationsConfigMock.Setup(x => x.Value).Returns(notificationsConfig);
        var mockClients = new Mock<IHubClients>();
        var mockClientProxy = new Mock<IClientProxy>();
        mockClients.Setup(clients => clients.Group(It.IsAny<string>())).Returns(mockClientProxy.Object);
        notificationHub.Setup(x => x.Clients).Returns(() => mockClients.Object);

        var unreadNotifications = new Faker<Notification>().GenerateBetween(0, faker.Random.Number(10));
        notificationRepositoryMock
            .Setup(x => x.GetByFilter(It.IsAny<Expression<Func<Notification, bool>>>(), It.IsAny<string>()))
            .Returns(Task.FromResult(unreadNotifications.AsEnumerable()));
        notificationRepositoryMock.Setup(x => x.Create(It.IsAny<Notification>())).Returns<Notification>(Task.FromResult);

        // Act
        await notificationService.Create(
            It.IsAny<NotificationType>(),
            It.IsAny<NotificationAction>(),
            It.IsAny<Guid>(),
            recipientsIds
        ).ConfigureAwait(false);

        // Assert
        notificationRepositoryMock.Verify(x => x.Create(It.IsAny<Notification>()), Times.Exactly(recipientsIds.Count()));
        foreach (var recipientId in recipientsIds)
            notificationHub.Verify(x => x.Clients.Group(recipientId), Times.Once);

        var countOfUnread = $"unreadNotificationsCount\":{unreadNotifications.Count}";
        mockClientProxy.Verify(x => x.SendCoreAsync(
                "ReceiveNotification",
                It.Is<object[]>(
                    arg => arg.Length > 0
                        && arg[0].ToString().Contains(countOfUnread)
                        && recipientsIds.Any(id => arg[0].ToString().Contains(id))
                ),
                It.IsAny<CancellationToken>()
            ), Times.Exactly(recipientsIds.Count()));
    }

```

**Review by VadymLevkovskyi — APPROVED** [review]

**Comment by OleksSavchenko** [comment]
> > As I believe this code is pretty much untestable. The issue is that ClientProxyExtensions class(for SendAsync method) block for some reason setupping ...
> 
> Everything is possible ;)
> 
> `.Setup()` for extension method is blocked because it's not the part of the mocked object and moreover is a static method (that can't be mocked). But you could go deeper and check what is called by that extension method - either reading source code or checking invocations list (`mock.Invocations`) for the mocked object. And `.Setup()`/`.Verify()` that invocations. See code below.
> 
> ```
>     [Test]
>     public async Task Create_RecipientsIdsValid_CreatesSpecificNumberOfTimesAndSendNotifications()
>     {
>         // Arrange
>         var faker = new Faker();
>         var recipientsIds = faker.Make(faker.Random.Int(1, 10), () => Guid.NewGuid().ToString());
> 
>         var notificationsConfig = new NotificationsConfig
>         {
>             Enabled = true,
>         };
> 
>         notificationsConfigMock.Setup(x => x.Value).Returns(notificationsConfig);
>         var mockClients = new Mock<IHubClients>();
>         var mockClientProxy = new Mock<IClientProxy>();
>         mockClients.Setup(clients => clients.Group(It.IsAny<string>())).Returns(mockClientProxy.Object);
>         notificationHub.Setup(x => x.Clients).Returns(() => mockClients.Object);
> 
>         var unreadNotifications = new Faker<Notification>().GenerateBetween(0, faker.Random.Number(10));
>         notificationRepositoryMock
>             .Setup(x => x.GetByFilter(It.IsAny<Expression<Func<Notification, bool>>>(), It.IsAny<string>()))
>             .Returns(Task.FromResult(unreadNotifications.AsEnumerable()));
>         notificationRepositoryMock.Setup(x => x.Create(It.IsAny<Notification>())).Returns<Notification>(Task.FromResult);
> 
>         // Act
>         await notificationService.Create(
>             It.IsAny<NotificationType>(),
>             It.IsAny<NotificationAction>(),
>             It.IsAny<Guid>(),
>             recipientsIds
>         ).ConfigureAwait(false);
> 
>         // Assert
>         notificationRepositoryMock.Verify(x => x.Create(It.IsAny<Notification>()), Times.Exactly(recipientsIds.Count()));
>         foreach (var recipientId in recipientsIds)
>             notificationHub.Verify(x => x.Clients.Group(recipientId), Times.Once);
> 
>         var countOfUnread = $"unreadNotificationsCount\":{unreadNotifications.Count}";
>         mockClientProxy.Verify(x => x.SendCoreAsync(
>                 "ReceiveNotification",
>                 It.Is<object[]>(
>                     arg => arg.Length > 0
>                         && arg[0].ToString().Contains(countOfUnread)
>                         && recipientsIds.Any(id => arg[0].ToString().Contains(id))
>                 ),
>                 It.IsAny<CancellationToken>()
>             ), Times.Exactly(recipientsIds.Count()));
>     }
> ```

Thank you for pointing out on this implementation. I've fixed this test and added new for another Create method.

**Pull request merged**
